In [2]:
import numpy as np
np.random.seed(0)

### Shape and distribution of `rand` vs `randn`

- Apparently i have to use (num_inputs, num_ouputs). This might be due to later dot product calculation. Intuitively i would have initialized it the other way around.
- Using normal distribution instead of uniform distribution apparently helps preventing vanishing gradients

In [6]:
num_inputs, num_outputs = 2, 3
weights = np.random.rand(num_inputs, num_outputs) # uniform distribution
weights2 = np.random.randn(num_inputs, num_outputs) # normal distribution
print(weights)
print(weights2)

[[0.61209572 0.616934   0.94374808]
 [0.6818203  0.3595079  0.43703195]]
[[-0.34791215  0.15634897  1.23029068]
 [ 1.20237985 -0.38732682 -0.30230275]]


### Testing np.zeros() behaviour

- The output looks different but in the implementation, it doesn't have an affect

In [7]:
print(np.zeros((num_outputs)))
print(np.zeros((1, num_outputs)))

[0. 0. 0.]
[[0. 0. 0.]]
